### ISSUE TITLE
Add internal error handling

### ISSUE THREAD

**Issue by Olivia5k** [thiderman/piper#1]
The distributed nature of this project makes for a hard time figuring out if something goes awry with the project itself. As such, we want them to report to specific points whenever internal errors (i.e. the script itself dying, not a test failure).

[Sentry](https://getsentry.com/welcome/) seems like the best fit as a general purpose solution.
## Todo
- [ ] Add required `sentry` field to `piperd.yml`.
- [ ] Add Sentry code to agent launch.
- [ ] Add piper-specific data to the error report. Good start would be the `piperd.yml` and the currently running build configuration.
##### Optional nice to haves
- [ ] Email logging if Sentry should be unavailable. Should be pretty simple with [Logbook](http://pythonhosted.org/Logbook/).
