### ISSUE TITLE
Add caching of repositories

### ISSUE THREAD

**Issue by Olivia5k** [thiderman/piper#13]
Repositories that need to be built a lot are usually quite large in size. A lot of time and electricity is wasted in most build systems by cloning the repositories over and over again. As repositories grow, this can add minutes to the total build time. This is silly and easy to overcome.

My suggested clone workflow for agents (repo `entity/repo.git` used as example):
- Check if `$REPOCACHE/entity/repo` exists. If it does not, do a bare clone into it. If it does, `fetch -a`.
- Clone the bare repo into `$WORKSPACE`.
## Todo
- [ ] Implement the above.
- [ ] Add `gitcache` configuration field to `piperd.yml`.
- [ ] Add optional cache size limiting. Once the limit is reached, delete the least used repositories until the size is below the limit again.
##### Nice to haves
- [ ] Add support for forks. That way forks of large repositories don't need their own cache entry - they can just use the upstream and apply the patches from the fork.
