### ISSUE TITLE
Refactor old tests

### ISSUE THREAD

**Issue by thiderman** [thiderman/piper#40]
Because of new things and especially the discovery of new and awesome `py.test` plugins, tests outside of API and Agent tests are using old-style `setup_method` style setups. They should be rewritten to use `py.test` fixtures instead for cleanliness and concision.

## Todo
- [ ] Implement usage of `py.test` fixtures.
- [ ] Add `@pytest.mark.randomize` calls to try things with different inputs in the same tests.
- [ ] Remove the test base class hierarchy.
- [ ] Move common test fixtures to a `test/fixtures.py` file.
